In [1]:
import pandas as pd
import re
from datetime import datetime, timedelta

In [2]:
df = pd.read_csv("data/vpn.log")

In [3]:
df = df.drop(columns=["Node", "Service", "Active", "Proto", "Port", "Error"])
df[["Duration"]] = df[["Duration"]].fillna(value=0)
df['Start Time'] = pd.to_datetime(df['Start Time'])
df["Duration"] = df["Duration"].apply(lambda x: timedelta(0, x))
end_time = df["Start Time"] + df["Duration"]
df.insert(2, "End Time", end_time)

/Users/jio/repo/github.com/diohabara/cs6322-f22/nsa-codebreak-challenge2022/.venv/lib/python3.10/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "

In [4]:
df = df.sort_values("Start Time")
df.sort_values("Start Time", ascending=True)

,Username,Start Time,End Time,Duration,Auth,Real Ip,Vpn Ip,Bytes Total
0,Doris.X,2022-06-27 07:48:08,2022-06-27 18:13:02,0 days 10:24:54,1,172.28.168.133,10.128.20.108,2.030863e+09
1,Kelly.G,2022-06-27 08:15:32,2022-06-27 17:14:06,0 days 08:58:34,1,172.19.185.189,10.128.20.194,2.363123e+09
2,Dorothy.D,2022-06-27 08:43:39,2022-06-27 13:46:43,0 days 05:03:04,1,172.22.90.19,10.128.20.43,2.009805e+09
3,James.V,2022-06-27 08:54:02,2022-06-27 09:31:48,0 days 00:37:46,1,172.25.206.19,10.128.20.78,1.379042e+08
4,Joan.P,2022-06-27 09:28:35,2022-06-27 15:03:09,0 days 05:34:34,1,172.23.234.95,10.128.20.106,1.318902e+09
...,...,...,...,...,...,...,...,...
171,Melissa.H,2022-07-02 16:44:22,2022-07-02 17:17:26,0 days 00:33:04,1,172.20.0.187,10.128.20.253,4.208461e+07
172,Martha.W,2022-07-02 17:05:25,2022-07-02 18:07:10,0 days 01:01:45,1,172.24.177.128,10.128.20.144,4.153750e+08
173,Brian.A,2022-07-02 17:19:27,2022-07-02 18:06:55,0 days 00:47:28,1,172.31.14.94,10.128.20.246,2.598601e+08
174,Sara.E,2022-07-02 17:54:05,2022-07-02 18:16:43,0 days 00:22:38,1,172.28.229.20,10.128.20.216,2.985699e+07
175,Michael.K,2022-07-02 18:09:05,2022-07-02 19:53:47,0 days 01:44:42,1,172.18.75.206,10.128.20.40,7.637907e+08